# Dataset information
dataset_name: syncan
data_type: training  # testing (override)

# Directories
root_dir: 'none'  # Dummy value, will be assigned dynamically
data_dir: 'none'  # Dummy value, will be assigned dynamically
train_data_dir: ../../datasets/can-ids/syncan/ambients
test_data_dir: ../../datasets/can-ids/syncan/attacks
scaler_dir: ../scaler/
features_dir: ../artifacts/features/
results_dir: ../artifacts/results/
plot_dir: ../artifacts/figures/

# Features
org_features:
  - 'Label'
  - 'Time'
  - 'ID'
  - 'Signal1_of_ID'
  - 'Signal2_of_ID'
  - 'Signal3_of_ID'
  - 'Signal4_of_ID'

features:
  - 'Sig_1_of_ID_2'
  - 'Sig_1_of_ID_7'
  - 'Sig_2_of_ID_3'
  - 'Sig_1_of_ID_10'
  - 'Sig_1_of_ID_9'
  - 'Sig_1_of_ID_1'
  - 'Sig_4_of_ID_10'
  - 'Sig_2_of_ID_2'
  - 'Sig_3_of_ID_10'
  - 'Sig_1_of_ID_6'
  - 'Sig_2_of_ID_5'
  - 'Sig_1_of_ID_4'
  - 'Sig_1_of_ID_5'
  - 'Sig_3_of_ID_2'
  - 'Sig_1_of_ID_8'
  - 'Sig_2_of_ID_6'
  - 'Sig_2_of_ID_10'
  - 'Sig_2_of_ID_7'
  - 'Sig_2_of_ID_1'
  - 'Sig_1_of_ID_3'

# Attributes
attributes:
  - 'File'
  - 'Feature'
  - 'Window'
  - 'Label'

# CANTropy Parameters
windsizes: [500]
batch_size: 1000000
domain_list: ['temporal', 'statistical']
varianceThresholds: [0.0, 0.005, 0.01, 0.015, 0.02]

# Additional parameters
num_signals: 20
dataset_fraction: 1.00  # (0.00 - 1.00] where 1.00 means evaluation on 100% of data points
